name: "oblivion_launcher"
description: "Obliv1on - A Minecraft Launcher"
publish_to: "none"
version: "1.0.3+3"
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: "flutter"
  flutter_localizations:
    sdk: "flutter"
  collection: "^1.18.0"
  provider: "^6.1.2"
  http: "^1.2.0"
  path_provider: "^2.1.2"
  path: "^1.9.0"
  crypto: "^3.0.3"
  archive: "^3.6.1"
  url_launcher: "^6.2.5"
  file_picker: "^8.0.0+1"
  shared_preferences: "^2.2.2"
  window_manager: "^0.3.8"
  desktop_drop: "^0.4.4"
  flutter_acrylic: ^1.1.4
  cached_network_image: ^3.3.1
  flutter_colorpicker: ^1.1.0
  package_info_plus: ^9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/NotoSansSC-6.ttf
