display_name: Oblivion Launcher
package_name: oblivion-launcher
executable_name: oblivion_launcher
icon: assets/icon.png
publisher: Aestat1s Team
description: Obliv1on - A Minecraft Launcher
maintainer:
  name: Aestat1s Team
  email: obliv1on@aestat1s.com
homepage: https://github.com/Aestat1s/Oblivion
license: MIT
version: 1.0.3
build_number: 1
app_id: com.oblivion.launcher
identifier: com.oblivion.launcher
priority: optional
section: games
installed_size: 102400
essential: false
status: install ok installed
architecture: amd64
