display_name: Oblivion Launcher
executable_name: oblivion_launcher
icon: assets/icon.png
publisher: Aestat1s Team
description: Obliv1on - A Minecraft Launcher
maintainer: Aestat1s Team <obliv1on@aestat1s.com>
version: 1.0.3
build_number: 1
app_id: com.oblivion.launcher
